artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://huggingface.co/datasets/Samsung/samsum/resolve/main/data/corpus.7z?download=true
  local_data_file: artifacts/data_ingestion/corpus.7z
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train.json", "test.json", "val.json"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion
  tokenizer: "google/pegasus-cnn_dailymail"

model_trainer:
  root-dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv
