artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://huggingface.co/datasets/Samsung/samsum/resolve/main/data/corpus.7z?download=true
  local_data_file: artifacts/data_ingestion/corpus.7z
  unzip_dir: artifacts/data_ingestion
